PRODUCT_VERSION_MAJOR = v030

ifdef CYANOGEN_NIGHTLY
    CMVERSION := v030
else
    ifdef CYANOGEN_RELEASE
        CMVERSION := GingerDX-$(PRODUCT_VERSION_MAJOR)-$(CM_BUILD)
    else
        CMVERSION := GingerDX-$(PRODUCT_VERSION_MAJOR)-$(CM_BUILD)
    endif
endif

PRODUCT_PROPERTY_OVERRIDES += \
    ro.modversion=$(CMVERSION)
PRODUCT_PROPERTY_OVERRIDES += \
    ro.gdx.version.id=$(PRODUCT_VERSION_MAJOR)
