PRODUCT_VERSION_MAJOR = v029

ifdef CYANOGEN_NIGHTLY
    CMVERSION := GingerDX-$(shell date +%Y%m%d)-NIGHTLY-$(CM_BUILD)
else
    ifdef CYANOGEN_RELEASE
        CMVERSION := GingerDX-$(PRODUCT_VERSION_MAJOR)-$(CM_BUILD)
    else
        CMVERSION := GingerDX-$(PRODUCT_VERSION_MAJOR)-$(CM_BUILD)-UNOFFICIAL
    endif
endif

PRODUCT_PROPERTY_OVERRIDES += \
    ro.modversion=$(CMVERSION)
